<?php
/*
 * Copyright (c) 2008, Conor McDermottroe
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the author nor the names of any contributors to the 
 *    software may be used to endorse or promote products derived from this 
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* XXX Autogenerated - do not edit XXX*/
/**	@package vBulletinAPI
 *	@filesource
 */

/** The base class. */
include_once("DataObject.php");

/** A query object for the search function.
 *
 *	@property	array $keywords Keywords to search for.
 *	@property	User $user		Restrict to this user.
 *	@property	DateTime $minDate	The earliest date/time to search for.
 *	@property	DateTime $maxDate	The latest date/time to search for.
 *	@property	int $minReplies The minimum number of replies that must be in
 *								the thread containing each returned post.
 *	@property	int $maxReplies The maximum number of replies that must be in
 *								the thread containing each returned post.
 *	@package	vBulletinAPI
 */
class SearchQuery
extends DataObject
{
	/** Create a new {@link SearchQuery}.
	 *
	 *	@param	array $keywords Keywords to search for.
	 *	@param	User $user		Restrict to this user.
	 *	@param	DateTime $minDate	The earliest date/time to search for.
	 *	@param	DateTime $maxDate	The latest date/time to search for.
	 *	@param	int $minReplies The minimum number of replies that must be in
	 *							the thread containing each returned post.
	 *	@param	int $maxReplies The maximum number of replies that must be in
	 *							the thread containing each returned post.
	 */
	public function __construct($keywords = array(), User $user = NULL, DateTime $minDate = NULL, DateTime $maxDate = NULL, $minReplies = 0, $maxReplies = 4294967295) {
		$this->data['keywords'] = $keywords;
		$this->data['user'] = $user;
		$this->data['minDate'] = $minDate;
		$this->data['maxDate'] = $maxDate;
		$this->data['minReplies'] = $minReplies;
		$this->data['maxReplies'] = $maxReplies;
	}

	/** Default values for the properties. These will be used to minimise the 
	 *	data to be sent over the wire.
	 *
	 *	@return	array	Default values for properties which have them.
	 */
	protected function defaultPropertyValues() {
		return array(
			"keywords" => array(),
			"user" => NULL,
			"minDate" => NULL,
			"maxDate" => NULL,
			"minReplies" => 0,
			"maxReplies" => 4294967295,
		);
	}
}
?>
